### ISSUE TITLE
Update to new YAML config file format in MongoDB >= 2.6

### ISSUE THREAD

**Issue by hackel** [saltstack-formulas/mongodb-formula#31]
I don't have time to do this now, but I wanted to make a note of it.  The current mongodb.conf file uses the old Mongo 2.4 config format.  The newer format should be much easier, especially since we can have a 1:1 mapping with our pillar file.  Here's the default file for reference:
```yaml
# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# network interfaces
net:
  port: 27017
  bindIp: 0.0.0.0


#processManagement:

#security:

#operationProfiling:

#replication:

#sharding:

## Enterprise-Only Options:

#auditLog:

#snmp:
```

Note that this also switches to using syslogd, which seems like a good thing.
