### ISSUE TITLE
Service name is wrong on Debian

### ISSUE THREAD

**Issue by wwentland** [saltstack-formulas/mongodb-formula#9]
As discussed in #8 this formula uses `mongod` as service name for Debian (and other distributions of the same os_family) while it should be `mongodb`. This causes the following error during the installation on wheezy:

```
----------
          ID: mongodb_service
    Function: service.running
        Name: mongod
      Result: False
     Comment: Failed to start the service
     Changes:   
              ----------
              mongod:
                  False
```

Rather than extended support for the PPA it would be nice if this formula could support the standard packages in Debian and, if support for newer versions is needed, also wheezy-backports.
